name: Deploy Lambda Functions

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: AWS Credentials Configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: go mod download

      - name: Build and package Lambdas
        run: |
          mkdir -p bin
          mkdir -p dist
          for lambda in $(ls -d function/*/); do
            lambda_name=$(basename $lambda)
            GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -tags lambda.norpc -o bin/bootstrap $lambda/main.go
            zip -j dist/${lambda_name}.zip bin/bootstrap
          done

      - name: Upload to S3
        run: |
          for zip in dist/*.zip; do
            aws s3 cp $zip s3://${{secrets.LAMBDA_BUCKET}}/$(basename $zip)
          done

      - name: Update Lambda functions
        run: |
          for zip in dist/*.zip; do
            lambda_name=$(basename $zip .zip)
            aws lambda update-function-code --function-name $lambda_name --s3-bucket ${{secrets.LAMBDA_BUCKET}} --s3-key $(basename $zip)
          done
